language: python
stages:
  - test
  - name: docker-hub
    if: NOT type IN (pull_request)
  - name: deploy
    if: tag IS present
jobs:
  include:
    - stage: test
      script:
        - docker pull battlesnakeio/play:latest
        - docker build -t battlesnakeio/play:${TRAVIS_PULL_REQUEST_SHA:-latest} --cache-from battlesnakeio/play:latest .
        - docker run -e ENV=local battlesnakeio/play:${TRAVIS_PULL_REQUEST_SHA:-latest} pytest
        - docker run -v $(pwd):/app dlsteuer/black --check /app
        - docker run -v $(pwd):/app alpine/flake8 /app
    - stage: docker-hub
      script:
        - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
        - docker push battlesnakeio/play:latest
    - stage: deploy
      script:
        - docker login -u _json_key -p "`echo $GCLOUD_SERVICE_KEY | base64 --decode`" https://gcr.io
        - docker tag battlesnakeio/play:latest gcr.io/battlesnake-io/play:${TRAVIS_TAG}
        - docker push gcr.io/battlesnake-io/play:${TRAVIS_TAG}

