# Generated by Django 2.2.4 on 2019-08-26 20:01

from django.db import migrations, models
import util.time


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=util.time.today, null=True),
        ),
    ]
