# Generated by Django 2.2.4 on 2019-11-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("event", "0003_auto_20190826_2001")]

    operations = [migrations.RenameModel("Event", "OldEvent")]
