# Generated by Django 2.2.4 on 2019-11-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("event", "0005_auto_20191108_0345")]

    operations = [migrations.DeleteModel(name="OldEvent")]
