# Generated by Django 2.2.4 on 2019-08-20 04:12

from django.db import migrations


def forward_migration(apps, schema_editor):
    """ Populate Account objects for all Users """
    Account = apps.get_model("core", "Account")
    User = apps.get_model("authentication", "User")

    for user in User.objects.all():
        if not Account.objects.filter(user=user).exists():
            Account.objects.create(user=user, created=user.created)


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_auto_20190820_0409"),
        ("core", "0009_account"),
    ]

    operations = [migrations.RunPython(forward_migration, reverse_migration)]
