# Generated by Django 2.2.4 on 2019-08-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0010_data_20190820_0412")]

    operations = [
        migrations.AddField(
            model_name="snake",
            name="account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Account",
            ),
        )
    ]
