# Generated by Django 2.2.4 on 2019-08-20 06:06

from django.db import migrations


def forward_migration(apps, schema_editor):
    """ Connect Snakes to Accounts (using Profile) """
    Account = apps.get_model("core", "Account")
    Snake = apps.get_model("core", "Snake")

    for snake in Snake.objects.all():
        snake.account = Account.objects.get(user=snake.profile.user)
        snake.save()


def reverse_migration(apps, schema_editor):
    Snake = apps.get_model("core", "Snake")

    for snake in Snake.objects.all():
        snake.account = None
        snake.save()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_auto_20190820_0409"),
        ("core", "0011_snake_account"),
    ]

    operations = [migrations.RunPython(forward_migration, reverse_migration)]
