# Generated by Django 2.2.4 on 2019-08-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0014_auto_20190820_2019")]

    operations = [
        migrations.AlterField(
            model_name="snake",
            name="profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Profile",
            ),
        )
    ]
