# Generated by Django 2.2.4 on 2019-08-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0015_auto_20190820_2203")]

    operations = [
        migrations.RemoveField(model_name="snake", name="profile"),
        migrations.AlterField(
            model_name="snake",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snakes",
                to="core.Account",
            ),
        ),
    ]
