# Generated by Django 2.2.4 on 2019-08-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_data_20190819_2321"),
        ("core", "0016_auto_20190821_0416"),
    ]

    operations = [migrations.DeleteModel(name="Profile")]
