# Generated by Django 2.2.4 on 2019-08-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0018_contentreport")]

    operations = [
        migrations.AlterModelOptions(
            name="contentreport", options={"verbose_name": "Content Report"}
        )
    ]
