# Generated by Django 2.2.4 on 2019-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20191126_1755"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profile_slug",
            field=models.SlugField(blank=True),
        ),
    ]
