# Generated by Django 2.2.4 on 2019-11-26 22:58
from django.db import migrations
from django.utils.text import slugify


def forward_migration(apps, schema_editor):
    """ Populate Account.profile_slug and empty display names with User.username """
    Account = apps.get_model("core", "Account")

    for account in Account.objects.filter(profile_slug=""):
        account.profile_slug = slugify(account.user.username)
        # if the display name just happens to be empty or whitespace, set it to the username
        if not account.display_name.strip():
            account.display_name = account.user.username
        account.save()


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_account_profile_slug"),
    ]

    operations = [migrations.RunPython(forward_migration, reverse_migration)]
