# Generated by Django 2.2.4 on 2019-11-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20191128_0202"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account", old_name="profile_slug", new_name="username",
        ),
    ]
