# Generated by Django 2.2.4 on 2019-11-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20191129_0421"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="github_username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="account",
            name="display_name",
            field=models.CharField(max_length=100),
        ),
    ]
