# Generated by Django 2.2.4 on 2019-11-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_auto_20191129_2235"),
    ]

    operations = [migrations.RunPython(forward_migration, reverse_migration)]


def forward_migration(apps, schema_editor):
    """ Populate Account.github_username with User.username """
    Account = apps.get_model("core", "Account")

    for account in Account.objects.filter(profile_slug=""):
        account.github_username = account.user.username
        account.save()


def reverse_migration(apps, schema_editor):
    pass
