# Generated by Django 2.2.4 on 2019-11-08 03:44

import apps.common.fields
from django.db import migrations, models
import util.time


class Migration(migrations.Migration):

    initial = True

    dependencies = [("events", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "created",
                    apps.common.fields.CreatedDateTimeField(
                        blank=True, default=util.time.now, editable=False
                    ),
                ),
                (
                    "modified",
                    apps.common.fields.ModifiedDateTimeField(
                        blank=True, default=util.time.now, editable=False
                    ),
                ),
                (
                    "id",
                    apps.common.fields.ShortUUIDField(
                        max_length=128, prefix="evt", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="This field supports Markdown.",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, default=util.time.today, null=True),
                ),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                ("registration_url", models.URLField(blank=True, default="")),
                ("is_listed", models.BooleanField(default=False)),
            ],
            options={"abstract": False},
        )
    ]
