# Generated by Django 2.2.4 on 2019-11-08 04:46

import apps.common.fields
from django.db import migrations, models
import django.db.models.deletion
import util.time


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20190826_1928"),
        ("events", "0003_auto_20191108_0347"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "created",
                    apps.common.fields.CreatedDateTimeField(
                        blank=True, default=util.time.now, editable=False
                    ),
                ),
                (
                    "modified",
                    apps.common.fields.ModifiedDateTimeField(
                        blank=True, default=util.time.now, editable=False
                    ),
                ),
                (
                    "id",
                    apps.common.fields.ShortUUIDField(
                        max_length=128,
                        prefix="team_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True, default="")),
                ("profile_pic_url", models.URLField(blank=True, default="")),
                ("profile_pic_approved", models.BooleanField(default=False)),
                ("accounts", models.ManyToManyField(to="core.Account")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.Event"
                    ),
                ),
                (
                    "snake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.Snake"
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
