# Generated by Django 2.2.4 on 2019-11-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0004_team")]

    operations = [
        migrations.AddField(
            model_name="event", name="slug", field=models.SlugField(default="")
        )
    ]
