# Generated by Django 2.2.4 on 2019-11-08 04:54

from django.db import migrations
from django.utils.text import slugify


def forward_migration(apps, schema_editor):
    """ Populate Event.slug from Event.name """
    Event = apps.get_model("events", "Event")

    for event in Event.objects.filter(slug=""):
        event.slug = slugify(event.name)
        event.save()


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("events", "0005_event_slug")]

    operations = [migrations.RunPython(forward_migration, reverse_migration)]
