# Generated by Django 2.2.4 on 2019-11-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0006_auto_20191108_0454")]

    operations = [
        migrations.AlterField(
            model_name="event", name="slug", field=models.SlugField(unique=True)
        )
    ]
