# Generated by Django 2.2.4 on 2019-11-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0008_auto_20191108_1716")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        )
    ]
