# Generated by Django 2.2.4 on 2019-11-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0010_auto_20191108_1718")]

    operations = [
        migrations.RemoveField(model_name="event", name="registration_url"),
        migrations.AddField(
            model_name="event",
            name="allow_registration",
            field=models.BooleanField(default=False),
        ),
    ]
