# Generated by Django 2.2.4 on 2019-11-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0011_auto_20191108_1905")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tldr",
            field=models.TextField(
                blank=True, default="", help_text="This field supports Markdown."
            ),
        )
    ]
