# Generated by Django 2.2.4 on 2019-08-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tournament", "0007_tournament_engine_url")]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="engine_url",
            field=models.CharField(
                default="https://engine.battlesnake.com", max_length=128
            ),
        )
    ]
