# Generated by Django 2.2.4 on 2019-08-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tournament", "0009_auto_20190820_0409")]

    operations = [
        migrations.RemoveField(model_name="heatgame", name="game"),
        migrations.RemoveField(model_name="heatgame", name="heat"),
        migrations.AlterUniqueTogether(name="round", unique_together=None),
        migrations.RemoveField(model_name="round", name="tournament_bracket"),
        migrations.AlterUniqueTogether(name="snakeheat", unique_together=None),
        migrations.RemoveField(model_name="snakeheat", name="heat"),
        migrations.RemoveField(model_name="snakeheat", name="snake"),
        migrations.RemoveField(model_name="team", name="team_members"),
        migrations.RemoveField(model_name="tournament", name="snakes"),
        migrations.RemoveField(model_name="tournamentbracket", name="snakes"),
        migrations.RemoveField(model_name="tournamentbracket", name="tournament"),
        migrations.RemoveField(model_name="tournamentsnake", name="bracket"),
        migrations.RemoveField(model_name="tournamentsnake", name="snake"),
        migrations.RemoveField(model_name="tournamentsnake", name="team"),
        migrations.RemoveField(model_name="tournamentsnake", name="tournament"),
        migrations.DeleteModel(name="Heat"),
        migrations.DeleteModel(name="HeatGame"),
        migrations.DeleteModel(name="Round"),
        migrations.DeleteModel(name="SnakeHeat"),
        migrations.DeleteModel(name="Team"),
        migrations.DeleteModel(name="Tournament"),
        migrations.DeleteModel(name="TournamentBracket"),
        migrations.DeleteModel(name="TournamentSnake"),
    ]
