name: CI

on: [push]

jobs:

  format:
    name: Format (Black)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install black
    - name: Run Black
      run: black . --check

  lint:
    name: Lint (Flake8)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install flake8
    - name: Run Flake8
      run: flake8 .

  test:
    name: Tests (Django)
    runs-on: ubuntu-latest
    needs: [format,lint]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Run Django Tests
      env:
        DJANGO_SETTINGS_MODULE: settings.test
        DJANGO_SECRET_KEY: test
        GITHUB_CLIENT_ID: test
        GITHUB_CLIENT_SECRET: test
      run: |
        cd src
        python manage.py test

  build:
    name: Build (Docker)
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@master
    - name: Run Docker Build
      run: docker build -t battlesnake/play .
