name: Release

on:
  release:
    branches:
    - master

jobs:

  release:
    name: Push Image (GCR)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker Image
      run: docker build -t battlesnake/play .
    - name: Tag Docker Image
      uses: actions/docker/tag@master
      with:
        args: battlesnake/play gcr.io/${{ secrets.GCLOuD_PROJECT_ID }}/battlesnake/play
    - name: Authenticate Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Add GCR Docker Repository
      uses: actions/gcloud/cli@master
      with:
        args: auth configure-docker --quiet
    - name: Push Docker Image
      run: docker push gcr.io/${{ secrets.GCLOuD_PROJECT_ID }}/battlesnake/play



# action "Auth Google Cloud" {
#   uses = "actions/gcloud/auth@master"
#   secrets = ["GCLOUD_AUTH"]
#   needs = ["Tags Only"]
# }

# action "Add GCR to Docker" {
#   uses = "actions/gcloud/cli@master"
#   args = "auth configure-docker --quiet"
#   needs = ["Auth Google Cloud"]
# }

# action "Push Image to GCR" {
#   uses = "actions/gcloud/cli@master"
#   needs = ["Add GCR to Docker", "Tag Image for GCR"]
#   runs = "sh -c"
#   args = ["docker push gcr.io/battlesnake-com/battlesnake/play"]
# }
