name: Release

on:
  release:
    branches:
    - master

jobs:

  release:
    name: Push Image (GCR)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker Image
      run: docker build -t battlesnake/play .
    - name: Tag Docker Image
      run: |
        docker tag battlesnake/play:latest gcr.io/${{ secrets.GCLOuD_PROJECT_ID }}/battlesnake/play:$(GITHUB_REF)
        docker images

  debug:
    name: Debugging
    steps:
    - uses: actions/checkout@master
    - run: |
        docker images
        echo $GITHUB_REF


# workflow "Build Image" {
#   resolves = [
#     "Run Docker Build",
#   ]
#   on = "push"
# }

# action "Run Docker Build" {
#   uses = "actions/docker/cli@master"
#   args = "build -t battlesnake/play ."
# }

# workflow "Release to GCR" {
#   resolves = [
#     "Push Image to GCR",
#   ]
#   on = "release"
# }

# action "Tags Only" {
#   uses = "actions/bin/filter@master"
#   args = "tag v*"
#   needs = ["Run Docker Build"]
# }

# action "Tag Image for GCR" {
#   uses = "actions/docker/tag@master"
#   args = "battlesnake/play gcr.io/battlesnake-com/battlesnake/play"
#   needs = ["Tags Only"]
# }

# action "Auth Google Cloud" {
#   uses = "actions/gcloud/auth@master"
#   secrets = ["GCLOUD_AUTH"]
#   needs = ["Tags Only"]
# }

# action "Add GCR to Docker" {
#   uses = "actions/gcloud/cli@master"
#   args = "auth configure-docker --quiet"
#   needs = ["Auth Google Cloud"]
# }

# action "Push Image to GCR" {
#   uses = "actions/gcloud/cli@master"
#   needs = ["Add GCR to Docker", "Tag Image for GCR"]
#   runs = "sh -c"
#   args = ["docker push gcr.io/battlesnake-com/battlesnake/play"]
# }
