name: CI

on: [push, release]

jobs:

  format:
    name: Format (Black)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install black
    - name: Run Black
      run: black . --check

  lint:
    name: Lint (Flake8)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install flake8
    - name: Run Flake8
      run: flake8 .

  test:
    name: Tests (Django)
    runs-on: ubuntu-latest
    needs: [format,lint]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.6
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Run Django Tests
      env:
        DJANGO_SETTINGS_MODULE: settings.test
        DJANGO_SECRET_KEY: test
        GITHUB_CLIENT_ID: test
        GITHUB_CLIENT_SECRET: test
      run: |
        cd src
        python manage.py test

  build:
    name: Build (Docker)
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@master
    - name: Run Docker Build
      run: docker build -t battlesnake/play .

  release:
    name: Release (GCR)
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Releases Only
      # if: github.event_name == 'release'
      run: echo "Releasing build to GCR!"
    - name: Tag Docker Image
      run: docker tag battlesnake/play:latest battlesnake/play:github.event.tag


# workflow "Build Image" {
#   resolves = [
#     "Run Docker Build",
#   ]
#   on = "push"
# }

# action "Run Docker Build" {
#   uses = "actions/docker/cli@master"
#   args = "build -t battlesnake/play ."
# }

# workflow "Release to GCR" {
#   resolves = [
#     "Push Image to GCR",
#   ]
#   on = "release"
# }

# action "Tags Only" {
#   uses = "actions/bin/filter@master"
#   args = "tag v*"
#   needs = ["Run Docker Build"]
# }

# action "Tag Image for GCR" {
#   uses = "actions/docker/tag@master"
#   args = "battlesnake/play gcr.io/battlesnake-com/battlesnake/play"
#   needs = ["Tags Only"]
# }

# action "Auth Google Cloud" {
#   uses = "actions/gcloud/auth@master"
#   secrets = ["GCLOUD_AUTH"]
#   needs = ["Tags Only"]
# }

# action "Add GCR to Docker" {
#   uses = "actions/gcloud/cli@master"
#   args = "auth configure-docker --quiet"
#   needs = ["Auth Google Cloud"]
# }

# action "Push Image to GCR" {
#   uses = "actions/gcloud/cli@master"
#   needs = ["Add GCR to Docker", "Tag Image for GCR"]
#   runs = "sh -c"
#   args = ["docker push gcr.io/battlesnake-com/battlesnake/play"]
# }
